FROM registry.access.redhat.com/ubi8/ruby-30:1-162.1717588679

LABEL summary="The 3scale command line interface" \
      description="3scale toolbox is a set of tools to help you manage your 3scale product" \
      io.k8s.description="3scale toolbox is a set of tools to help you manage your 3scale product" \
      io.k8s.display-name="3scale Toolbox" \
      io.openshift.expose-services="" \
      io.openshift.tags="3scale, cli, toolbox, openapi, rubygems, rhamp"

ENV TZ=:/etc/localtime \
    DISABLE_SPRING=1

USER root

COPY ./rh-toolbox/toolbox /opt/toolbox

WORKDIR /opt/toolbox

RUN cd /opt/toolbox \
    && bundle config --local silence_root_warning 1 \
    && bundle config --local disable_shared_gems 1 \
    && bundle config --local without "development test" \
    && bundle config --local gemfile Gemfile

RUN cd /opt/toolbox/ \
    && bundle config list \
    && bundle install \
    && bundle binstubs 3scale_toolbox

RUN chmod +t /tmp

ENV PATH="/opt/toolbox/bin:${PATH}"

USER default

WORKDIR /opt/app-root/src

CMD ["/bin/bash"]
